swagger: "2.0"
info:
  title: The authorizor Service
  description: HTTP Service for managing identity
  version: ""
host: localhost:8088
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /ping:
    get:
      tags:
      - authorizor
      summary: ping authorizor
      operationId: authorizor#ping
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AuthorizorPingResponseBody'
            required:
            - health
      schemes:
      - http
  /register:
    post:
      tags:
      - authorizor
      summary: register authorizor
      operationId: authorizor#register
      parameters:
      - name: RegisterRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AuthorizorRegisterRequestBody'
          required:
          - username
          - password
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AuthorizorRegisterResponseBody'
            required:
            - code
            - refreshToken
            - accessToken
      schemes:
      - http
definitions:
  AuthorizorPingResponseBody:
    title: AuthorizorPingResponseBody
    type: object
    properties:
      health:
        type: string
        description: Return 'ok' if server is running
        example: Ut harum unde sed itaque molestias.
    example:
      health: Iure repudiandae et ad quo ut perspiciatis.
    required:
    - health
  AuthorizorRegisterRequestBody:
    title: AuthorizorRegisterRequestBody
    type: object
    properties:
      password:
        type: string
        description: password
        example: Quos facilis nihil.
      username:
        type: string
        description: username
        example: Aut sequi incidunt.
    example:
      password: Tenetur incidunt.
      username: Accusamus consectetur similique excepturi explicabo similique facilis.
    required:
    - username
    - password
  AuthorizorRegisterResponseBody:
    title: AuthorizorRegisterResponseBody
    type: object
    properties:
      accessToken:
        type: string
        description: jwt access token
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      code:
        type: string
        description: return code of registration
        example: c_success
      refreshToken:
        type: string
        description: jwt refresh token
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    example:
      accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      code: c_success
      refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    required:
    - code
    - refreshToken
    - accessToken
